### PR TITLE
Fix bug: editc and deletec do not update attendee

### LINKED ISSUE #102: deletec and editc commands have to update meeting attendees

### PR DESCRIPTION
**Pull request by howenc**
fix #102

### CODE REVIEW

**Review by LoMaply — DISMISSED** [review]
lgtm

**Review by jason-raiin — APPROVED** [review]
lgtm

**Review by jason-raiin — DISMISSED** [review]
need to unit test the `updateAttendee` and `deleteAttendee` methods and also integration test with `DeleteCommand` and `EditCommand`

**Review by LoMaply — APPROVED** [review]
Looks good

**Pull request merged**
